blog/urls.py
from django.urls import path
from .views import index_view, single_post

app_name = 'blog'
urlpatterns = [
    path('', index_view, name='index'),
    path('<str:id>', single_post, name='single_post'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts',include('django.contrib.auth.urls')),
    path('', include('blog.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from typing import OrderedDict
from venv import create
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.
class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    status = models.BooleanField(default=False) 
    tags = models.ManyToManyField('tag', blank=True)
    vote_total = models.IntegerField(null=True, blank=True, default=0)
    vote_ratio = models.IntegerField(null=True, blank=True, default=0)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                         primary_key=True, editable=False)
    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ['-created_date',]


class Review(models.Model):
    VOTE_TYPE =(
        ('up','Up Vote'),
        ('down','Down Vote')
    )
    #owner
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(blank=True, null=True)
    value = models.CharField(max_length=255, choices=VOTE_TYPE)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                         primary_key=True, editable=False)
    def __str__(self) -> str:
        return self.value
        
class Tag(models.Model):
    name = models.CharField(max_length=200)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                        primary_key=True, editable=False)

    def __str__(self) -> str:
        return self.name

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .models import Post, Tag, Review

# Create your views here.


def index_view(request):
    posts = Post.objects.filter(status=1)
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)
    context = {
        'page_object': page_object,
    }
    return render(request,'index.html', context)

def single_post(request, id):
    posts = Post.objects.filter(status=1)
    post = get_object_or_404(posts, id=id)
    reviews = Review.objects.filter(post=post.id)
    context = {
        'post': post,
        'reviews': reviews,
        }
    return render(request,'single-post.html', context)
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{% static 'img/fav.png' %}">
	<!-- Author Meta -->
	<meta name="author" content="colorlib">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>My Blog</title>

	<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
		<!--
		CSS
		============================================= -->
		<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
		<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">				
		<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">							
		<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">				
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
	</head>
	<body>	
		<header id="header">
			<div class="header-top">
				<div class="container">
				<div class="row align-items-center">
					<div class="col-lg-6 col-sm-6 col-6 header-top-left">
            
						{% comment %} <ul>
							<li><a href="#">Visit Us</a></li>
							<li><a href="#">Buy Tickets</a></li>
						</ul>		 {% endcomment %}

					</div>

					{% comment %} <div class="col-lg-6 col-sm-6 col-6 header-top-right">
						<div class="header-social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div> {% endcomment %}

				</div>			  					
				</div>
			</div>
			<div class="container main-menu">
				<div class="row align-items-center justify-content-between d-flex">
					<div id="logo">
					<a href="index.html"><img src="{% static 'img/logo.png' %}" alt="" title="" /></a>
					</div>
					<nav id="nav-menu-container">
					<ul class="nav-menu">
						<li><a href="{% url 'blog:index' %}">Home</a></li>
						<li><a href="#">About</a></li>

            <!--
						<li><a href="packages.html">Packages</a></li>
						<li><a href="hotels.html">Hotels</a></li>
						<li><a href="insurance.html">Insurence</a></li>
						<li class="menu-has-children"><a href="">Blog</a>
						<ul>
							<li><a href="blog-home.html">Blog Home</a></li>
							<li><a href="blog-single.html">Blog Single</a></li>
						</ul>
						</li>	
						<li class="menu-has-children"><a href="">Pages</a>
						<ul>
								<li><a href="elements.html">Elements</a></li>
								<li class="menu-has-children"><a href="">Level 2 </a>
								<ul>
									<li><a href="#">Item One</a></li>
									<li><a href="#">Item Two</a></li>
								</ul>
								</li>					                		
						</ul>
						</li>					          					          		          
						<li><a href="contact.html">Contact</a></li>
            -->

					</ul>
					</nav><!-- #nav-menu-container -->					      		  
				</div>
			</div>
		</header><!-- #header -->


    {% block content %}
    {% endblock content %}
<!--
<!-- start footer Area 		
  <footer class="footer-area section-gap">
		<div class="container">

			<div class="row">
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>About Agency</h6>
						<p>
							The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point 
						</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Navigation Links</h6>
						<div class="row">
							<div class="col">
								<ul>
									<li><a href="#">Home</a></li>
									<li><a href="#">Feature</a></li>
									<li><a href="#">Services</a></li>
									<li><a href="#">Portfolio</a></li>
								</ul>
							</div>
							<div class="col">
								<ul>
									<li><a href="#">Team</a></li>
									<li><a href="#">Pricing</a></li>
									<li><a href="#">Blog</a></li>
									<li><a href="#">Contact</a></li>
								</ul>
							</div>										
						</div>							
					</div>
				</div>							
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Newsletter</h6>
						<p>
							For business professionals caught between high OEM price and mediocre print and graphic output.									
						</p>								
						<div id="mc_embed_signup">
							<form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscription relative">
								<div class="input-group d-flex flex-row">
									<input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
									<button class="btn bb-btn"><span class="lnr lnr-location"></span></button>		
								</div>									
								<div class="mt-10 info"></div>
							</form>
						</div>
					</div>
				</div>
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget mail-chimp">
						<h6 class="mb-20">InstaFeed</h6>
						<ul class="instafeed d-flex flex-wrap">
							<li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
							<li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
						</ul>
					</div>
				</div>						
			</div>

			<div class="row footer-bottom d-flex justify-content-between align-items-center">
				
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
</p>
				<div class="col-lg-4 col-sm-12 footer-social">
					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-dribbble"></i></a>
					<a href="#"><i class="fa fa-behance"></i></a>
				</div>
			</div>
		</div>
  </footer>
	 End footer Area -->	


	<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>			
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>		
	<script src="{% static 'js/jquery-ui.js' %}"></script>					
	<script src="{% static 'js/easing.min.js' %}"></script>			
	<script src="{% static 'js/hoverIntent.js' %}"></script>
	<script src="{% static 'js/superfish.min.js' %}"></script>	
	<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>						
	<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>					
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>							
	<script src="{% static 'js/mail-script.js' %}"></script>	
	<script src="{% static 'js/main.js' %}"></script>	
</body>
</html>

templates/single-post.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}	
<!-- start banner Area -->
<section class="relative about-banner">	
	<div class="overlay overlay-bg"></div>
	<div class="container">				
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{ post.title }}				
				</h1>	
				<p class="text-white link-nav"><a href="{% url 'blog:index' %}">Home </a> <span class="lnr lnr-arrow-right"></span> <a href="blog-single.html">{{ post.title }}</a></p>
			</div>	
		</div>
	</div>
</section>
<!-- End banner Area -->					  

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
							<img class="img-fluid" src="{{ post.image.url }}" alt="">
						</div>									
					</div>
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for tag in post.tags.all  %}
							<li><a href="#">{{ tag.name }}</a> {% if not forloop.last %},{% endif %}</li>
							{% endfor %}
						</ul> 
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{post.author.username}}</a> <span class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|naturalday}}</a> <span class="lnr lnr-calendar-full"></span></p>
							{% comment %} <p class="view col-lg-12 col-md-12 col-6"><a href="#">1.2M Views</a> <span class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>
							<ul class="social-links col-lg-12 col-md-12 col-6">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-github"></i></a></li>
								<li><a href="#"><i class="fa fa-behance"></i></a></li>
							</ul>																				 {% endcomment %}
						</div>
					</div>
					<div class="col-lg-9 col-md-9">
						<h3 class="mt-20 mb-20">{{post.title}}</h3>
						<p class="excert">
							{{post.content}}
						</p>
					</div>
					
				</div>
				<div class="navigation-area">
					<div class="row">
						<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
							<div class="thumb">
								{% if post.get_previous_by_created_date %}
								<a href="{% url 'blog:single_post' post.get_previous_by_created_date.id %}"><img class="img-fluid" src="{{ post.get_previous_by_created_date.image.url }}" alt=""></a>
							</div>
							<div class="arrow">
								<a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
							</div>
							<div class="detials">
								<p>Prev Post</p>
								
								<a href="{% url 'blog:single_post' post.get_previous_by_created_date.id %}"><h4>{{ post.get_previous_by_created_date.title }}</h4></a>
								{% endif %}
							</div>
						</div>
						<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
							<div class="detials">
								{% if post.get_next_by_created_date %}
								<p>Next Post</p>
								<a href="{% url 'blog:single_post' post.get_next_by_created_date.id %}"><h4>{{ post.get_next_by_created_date.title }}</h4></a>
							</div>
							<div class="arrow">
								<a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
							</div>
							<div class="thumb">
								<a href="{% url 'blog:single_post' post.get_next_by_created_date.id %}"><img class="img-fluid" src="{{ post.get_next_by_created_date.image.url }}" alt=""></a>
								{% endif %}
							</div>										
						</div>									
					</div>
				</div>
				
				<div class="comments-area">
					{% if reviews %}
					<h4>{{reviews|length}}{% if reviews|length > 1 %}comments{% else %}comment{% endif %}</h4>
					<div class="comment-list">
						{% for review in reviews %}
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">				
									{% if review.value == 'up' %}
									<img src="{% static 'img/blog/like.jpg' %}" alt="">
									{% else %}
									<img src="{% static 'img/blog/dislike.jpg' %}" alt="">
									{% endif %}
								</div> 
								<div class="desc">
									
									<h5><a href="#">{{review.value}}</a></h5>
									<p class="date">{{review.created_date|naturaltime}} </p>
									<p class="comment">
										{{ review.body }}
									</p>
									
								</div>
							</div>
							{% comment %} <div class="reply-btn">
									<a href="" class="btn-reply text-uppercase">reply</a> 
							</div> {% endcomment %}
						</div>
						{% endfor %}
					</div>
					{% endif %}	                                          				
				</div>

				{% comment %} <div class="comment-form">
					<h4>Leave a Comment</h4>
					<form>
						<div class="form-group form-inline">
							<div class="form-group col-lg-6 col-md-12 name">
							<input type="text" class="form-control" id="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
							</div>
							<div class="form-group col-lg-6 col-md-12 email">
							<input type="email" class="form-control" id="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
							</div>										
						</div>
						<div class="form-group">
							<input type="text" class="form-control" id="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
						</div>
						<div class="form-group">
							<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
						</div>
						<a href="#" class="primary-btn text-uppercase">Post Comment</a>	
					</form>
				</div> {% endcomment %}

			</div>
		<!--
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					<div class="single-sidebar-widget search-widget">
						<form class="search-form" action="#">
							<input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
							<button type="submit"><i class="fa fa-search"></i></button>
						</form>
					</div>
					<div class="single-sidebar-widget user-info-widget">
						<img src="{% static 'img/blog/user-info.png' %}" alt="">
						<a href="#"><h4>Charlie Barber</h4></a>
						<p>
							Senior blog writer
						</p>
						<ul class="social-links">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-github"></i></a></li>
							<li><a href="#"><i class="fa fa-behance"></i></a></li>
						</ul>
						<p>
							Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
						</p>
					</div>
					<div class="single-sidebar-widget popular-post-widget">
						<h4 class="popular-title">Popular Posts</h4>
						<div class="popular-post-list">
							<div class="single-post-list d-flex flex-row align-items-center">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/blog/pp1.jpg' %}" alt="">
								</div>
								<div class="details">
									<a href="blog-single.html"><h6>Space The Final Frontier</h6></a>
									<p>02 Hours ago</p>
								</div>
							</div>
							<div class="single-post-list d-flex flex-row align-items-center">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/blog/pp2.jpg' %}" alt="">
								</div>
								<div class="details">
									<a href="blog-single.html"><h6>The Amazing Hubble</h6></a>
									<p>02 Hours ago</p>
								</div>
							</div>
							<div class="single-post-list d-flex flex-row align-items-center">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/blog/pp3.jpg' %}" alt="">
								</div>
								<div class="details">
									<a href="blog-single.html"><h6>Astronomy Or Astrology</h6></a>
									<p>02 Hours ago</p>
								</div>
							</div>
							<div class="single-post-list d-flex flex-row align-items-center">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/blog/pp4.jpg' %}" alt="">
								</div>
								<div class="details">
									<a href="blog-single.html"><h6>Asteroids telescope</h6></a>
									<p>02 Hours ago</p>
								</div>
							</div>															
						</div>
					</div>
					<div class="single-sidebar-widget ads-widget">
						<a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
					</div>
					<div class="single-sidebar-widget post-category-widget">
						<h4 class="category-title">Post Catgories</h4>
						<ul class="cat-list">
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Technology</p>
									<p>37</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Lifestyle</p>
									<p>24</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Fashion</p>
									<p>59</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Art</p>
									<p>29</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Food</p>
									<p>15</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Architecture</p>
									<p>09</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Adventure</p>
									<p>44</p>
								</a>
							</li>															
						</ul>
					</div>	
					<div class="single-sidebar-widget newsletter-widget">
						<h4 class="newsletter-title">Newsletter</h4>
						<p>
							Here, I focus on a range of items and features that we use in life without
							giving them a second thought.
						</p>
						<div class="form-group d-flex flex-row">
							<div class="col-autos">
								<div class="input-group">
								<div class="input-group-prepend">
									<div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
								</div>
								</div>
								<input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
								</div>
							</div>
							<a href="#" class="bbtns">Subcribe</a>
						</div>	
						<p class="text-bottom">
							You can unsubscribe at any time
						</p>								
					</div>
					<div class="single-sidebar-widget tag-cloud-widget">
						<h4 class="tagcloud-title">Tag Clouds</h4>
						<ul>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Architecture</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Art</a></li>
							<li><a href="#">Adventure</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Adventure</a></li>
						</ul>
					</div>								
				</div>
			</div>
		-->
		</div>
	</div>	
</section>
<!-- End post-content Area -->
{% endblock content %}